kind: Service
apiVersion: v1
metadata:
  name: "service2"
  labels:
    app: "service2"
spec:
  selector:
    app: "service2"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 5550
      targetPort: 5550
      name: zmq1
    - protocol: TCP
      port: 5551
      targetPort: 5551
      name: zmq2
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "service2"
  labels:
    app: "service2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "service2"
  template:
    metadata:
      labels:
        app: "service2"
    spec:
      containers:
        - name: "service2"
          image: sleepymug/slowpoke-mutex-microbench
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_NAME
              value: "service2"
            - name: APP_NAME_NO_UNDERSCORES
              value: "service2"
            - name: APP_NAMESPACE
              value: "mutex"
            - name: NODE_IDX
              value: "2"
            - name: CM_ENABLED
              value: "false"
            - name: EXPIRATION_TTL
              value: "0"
            - name: SLOWPOKE_DELAY_MICROS
              value: "${SLOWPOKE_DELAY_MICROS_SERVICE2}"
            - name: SLOWPOKE_PRERUN
              value: "${SLOWPOKE_PRERUN}"
            - name: SLOWPOKE_PROCESSING_MICROS
              value: "${SLOWPOKE_PROCESSING_MICROS_SERVICE2}"
          ports:
            - containerPort: 3000
            - containerPort: 5550
            - containerPort: 5551
          imagePullPolicy: Always
