#!/bin/bash

cd $(dirname $0)

export SLOWPOKE_DELAY_MICROS_CART=0
export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
export SLOWPOKE_DELAY_MICROS_CURRENCY=0
export SLOWPOKE_DELAY_MICROS_EMAIL=0
export SLOWPOKE_DELAY_MICROS_FRONTEND=0
export SLOWPOKE_DELAY_MICROS_PAYMENT=0
export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
export SLOWPOKE_DELAY_MICROS_SHIPPING=0

request=home
thread=16
conn=1024
duration=60

bash run.sh $request $thread $conn $duration