kind: Service
apiVersion: v1
metadata:
  name: "productcatalog"
  labels:
    app: "productcatalog"
spec:
  selector:
    app: "productcatalog"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 5550
      targetPort: 5550
      name: zmq1
    - protocol: TCP
      port: 5551
      targetPort: 5551
      name: zmq2
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "productcatalog"
  labels:
    app: "productcatalog"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "productcatalog"
  template:
    metadata:
      labels:
        app: "productcatalog"
    spec:
      containers:
        - name: "productcatalog"
          image: sleepymug/mucache:prebuilt
          env:
            - name: APP_PORT
              value: "3000"
            - name: APP_NAME
              value: "product_catalog"
            - name: APP_NAME_NO_UNDERSCORES
              value: "productcatalog"
            - name: APP_NAMESPACE
              value: "boutique"
            - name: NODE_IDX
              value: "1"
            - name: CM_ENABLED
              value: "false"
            - name: EXPIRATION_TTL
              value: "0"
            - name: SLOWPOKE_DELAY_MICROS
              value: "${SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG}"
            - name: SLOWPOKE_PRERUN
              value: "${SLOWPOKE_PRERUN}"
          ports:
            - containerPort: 3000
            - containerPort: 5550
            - containerPort: 5551
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 1000m
              memory: 4Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1