#!/bin/bash

cd $(dirname $0)

# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PROCESSING_MICROS_CART=0
# export SLOWPOKE_PROCESSING_MICROS_CHECKOUT=0
# export SLOWPOKE_PROCESSING_MICROS_CURRENCY=0
# export SLOWPOKE_PROCESSING_MICROS_EMAIL=0
# export SLOWPOKE_PROCESSING_MICROS_FRONTEND=0
# export SLOWPOKE_PROCESSING_MICROS_PAYMENT=0
# export SLOWPOKE_PROCESSING_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_PROCESSING_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_PROCESSING_MICROS_SHIPPING=0
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_POKER_BATCH_THRESHOLD=40000000
# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PROCESSING_MICROS_FRONTEND=500
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=287
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2543
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=129
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2543
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=213
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1271
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=229
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2034
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=103
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2034
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=170
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1017
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_PRERUN=true
# export SLOWPOKE_DELAY_MICROS_COMPOSEPOST=0
# export SLOWPOKE_DELAY_MICROS_SOCIALGRAPH=0
# export SLOWPOKE_DELAY_MICROS_HOMETIMELINE=0
# export SLOWPOKE_DELAY_MICROS_USERTIMELINE=0
# export SLOWPOKE_DELAY_MICROS_POSTSTORAGE=0

export SLOWPOKE_DELAY_MICROS_SERVICE0=700
export SLOWPOKE_PROCESSING_MICROS_SERVICE0=10
export SLOWPOKE_DELAY_MICROS_SERVICE1=502
export SLOWPOKE_PROCESSING_MICROS_SERVICE1=32
export SLOWPOKE_DELAY_MICROS_SERVICE2=740
export SLOWPOKE_PROCESSING_MICROS_SERVICE2=12
export SLOWPOKE_DELAY_MICROS_SERVICE3=560
export SLOWPOKE_PROCESSING_MICROS_SERVICE3=50
export SLOWPOKE_DELAY_MICROS_SERVICE4=670
export SLOWPOKE_PROCESSING_MICROS_SERVICE4=20
export SLOWPOKE_DELAY_MICROS_SERVICE5=680
export SLOWPOKE_PROCESSING_MICROS_SERVICE5=70
export SLOWPOKE_DELAY_MICROS_SERVICE6=0
export SLOWPOKE_PROCESSING_MICROS_SERVICE6=709
export SLOWPOKE_DELAY_MICROS_SERVICE7=0
export SLOWPOKE_PROCESSING_MICROS_SERVICE7=310
export SLOWPOKE_DELAY_MICROS_SERVICE8=0
export SLOWPOKE_PROCESSING_MICROS_SERVICE8=110
export SLOWPOKE_DELAY_MICROS_SERVICE9=248
export SLOWPOKE_PROCESSING_MICROS_SERVICE9=91
export SLOWPOKE_DELAY_MICROS_SERVICE10=396
export SLOWPOKE_PROCESSING_MICROS_SERVICE10=92
export SLOWPOKE_DELAY_MICROS_SERVICE11=158
export SLOWPOKE_PROCESSING_MICROS_SERVICE11=64
export SLOWPOKE_DELAY_MICROS_SERVICE12=250
export SLOWPOKE_PROCESSING_MICROS_SERVICE12=62
export SLOWPOKE_DELAY_MICROS_SERVICE13=249
export SLOWPOKE_PROCESSING_MICROS_SERVICE13=6
export SLOWPOKE_DELAY_MICROS_SERVICE14=281
export SLOWPOKE_PROCESSING_MICROS_SERVICE14=0
export SLOWPOKE_DELAY_MICROS_SERVICE15=379
export SLOWPOKE_PROCESSING_MICROS_SERVICE15=76
export SLOWPOKE_DELAY_MICROS_SERVICE16=303
export SLOWPOKE_PROCESSING_MICROS_SERVICE16=15
export SLOWPOKE_DELAY_MICROS_SERVICE17=351
export SLOWPOKE_PROCESSING_MICROS_SERVICE17=45
export SLOWPOKE_DELAY_MICROS_SERVICE18=349
export SLOWPOKE_PROCESSING_MICROS_SERVICE18=93
export SLOWPOKE_DELAY_MICROS_SERVICE19=152
export SLOWPOKE_PROCESSING_MICROS_SERVICE19=86
export SLOWPOKE_DELAY_MICROS_SERVICE20=393
export SLOWPOKE_PROCESSING_MICROS_SERVICE20=95

# Setting
# One is service0-100 processing time, 300 delay?
# Another is service1-500 processing time, 100 delay?

export SLOWPOKE_POKER_BATCH_THRESHOLD=300



bash run.sh mutex x 1 1 10000
# DIR=/home/ubuntu/mucache/slowpoke/synthetic/two-services/interference-microbenchmark

# for threadshold in 10000000 20000000 30000000 40000000 50000000 60000000
# # for threadshold in 20000000
# do
#     export SLOWPOKE_POKER_BATCH_THRESHOLD=$threadshold
#     benchmark=synthetic
#     request=two-services
#     thread=8
#     conn=512
#     num_req=40000
#     # FILE=service1-base.log
#     FILE=service1-d300-poker$threadshold.log
#     env | grep "SLOWPOKE" >$DIR/$FILE
#     env | grep "PROCESSING" >>$DIR/$FILE
#     echo "bash run.sh $benchmark $request $thread $conn $num_req" >>$DIR/$FILE
#     bash run.sh $benchmark $request $thread $conn $num_req >>$DIR/$FILE
# done
