#!/bin/bash

cd $(dirname $0)

# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PROCESSING_MICROS_CART=0
# export SLOWPOKE_PROCESSING_MICROS_CHECKOUT=0
# export SLOWPOKE_PROCESSING_MICROS_CURRENCY=0
# export SLOWPOKE_PROCESSING_MICROS_EMAIL=0
# export SLOWPOKE_PROCESSING_MICROS_FRONTEND=0
# export SLOWPOKE_PROCESSING_MICROS_PAYMENT=0
# export SLOWPOKE_PROCESSING_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_PROCESSING_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_PROCESSING_MICROS_SHIPPING=0
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_POKER_BATCH_THRESHOLD=40000000
# export SLOWPOKE_DELAY_MICROS_CART=0
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=0
# export SLOWPOKE_DELAY_MICROS_CURRENCY=0
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=0
# export SLOWPOKE_DELAY_MICROS_PAYMENT=0
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=0
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=0
# export SLOWPOKE_PROCESSING_MICROS_FRONTEND=500
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=287
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2543
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=129
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2543
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=213
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1271
# export SLOWPOKE_PRERUN=false
# export SLOWPOKE_DELAY_MICROS_CART=229
# export SLOWPOKE_DELAY_MICROS_CHECKOUT=2034
# export SLOWPOKE_DELAY_MICROS_CURRENCY=1000
# export SLOWPOKE_DELAY_MICROS_EMAIL=0
# export SLOWPOKE_DELAY_MICROS_FRONTEND=103
# export SLOWPOKE_DELAY_MICROS_PAYMENT=2034
# export SLOWPOKE_DELAY_MICROS_PRODUCT_CATALOG=170
# export SLOWPOKE_DELAY_MICROS_RECOMMENDATIONS=0
# export SLOWPOKE_DELAY_MICROS_SHIPPING=1017
# export SLOWPOKE_PRERUN=false

# export SLOWPOKE_PRERUN=true
# export SLOWPOKE_DELAY_MICROS_COMPOSEPOST=0
# export SLOWPOKE_DELAY_MICROS_SOCIALGRAPH=0
# export SLOWPOKE_DELAY_MICROS_HOMETIMELINE=0
# export SLOWPOKE_DELAY_MICROS_USERTIMELINE=0
# export SLOWPOKE_DELAY_MICROS_POSTSTORAGE=0


# Setting
# One is service0-100 processing time, 300 delay?
# Another is service1-500 processing time, 100 delay?
export SLOWPOKE_POKER_BATCH_THRESHOLD=10000000

# export PROCESSING_TIME_SERVICE0=0.0002 # base
export PROCESSING_TIME_SERVICE0=0.0
export PROCESSING_TIME_SERVICE1=0.0005 # base
# export PROCESSING_TIME_SERVICE1=0.0
# export SLOWPOKE_DELAY_MICROS_SERVICE0=200
export SLOWPOKE_DELAY_MICROS_SERVICE0=0
# export SLOWPOKE_DELAY_MICROS_SERVICE1=0
export SLOWPOKE_DELAY_MICROS_SERVICE1=300


DIR=/home/ubuntu/mucache/slowpoke/synthetic/two-services/interference-microbenchmark

for threadshold in 40000000
# for threadshold in 20000000
do
    export SLOWPOKE_POKER_BATCH_THRESHOLD=$threadshold
    benchmark=synthetic
    request=two-services
    thread=8
    conn=512
    num_req=40000
    # FILE=service1-base.log
    FILE=service1-d300-poker$threadshold.log
    env | grep "SLOWPOKE" 
    env | grep "PROCESSING" 
    echo "bash run.sh $benchmark $request $thread $conn $num_req"
    bash run.sh $benchmark $request $thread $conn $num_req
done
